### ISSUE TITLE
What is the development status?

### ISSUE THREAD

**Issue by hasansezertasan** [apiad/auditorium#62]
Is this project abandoned or moved? I can not seem to find anything on the main branch and the documentation is broken.

**Comment by apiad** [comment]
Sadly I've tried to restart development a couple of times but as tech keeps
changing I keep finding that I would rather do it from scratch, and then
procrastination kicks in and I go off to work on other stuff. So it's
basically inactive for an undetermined amount of time. I'd love to revisit
this concept in the future but probably would do it differently.

**Comment by hasansezertasan** [comment]
> Sadly I've tried to restart development a couple of times but as tech keeps changing I keep finding that I would rather do it from scratch, and then procrastination kicks in and I go off to work on other stuff. So it's basically inactive for an undetermined amount of time. I'd love to revisit this concept in the future but probably would do it differently.

I see, looking forward to seeing the next release!

**Comment by hasansezertasan** [comment]
> Sadly I've tried to restart development a couple of times but as tech keeps changing I keep finding that I would rather do it from scratch, and then procrastination kicks in and I go off to work on other stuff. So it's basically inactive for an undetermined amount of time. I'd love to revisit this concept in the future but probably would do it differently.

I see, looking forward to seeing the next release!

**Comment by mayurankv** [comment]
Hi, I understand that this isn't at all a priority due to the development status but would it be possible to restore the documentation? I'm interested in understanding the project and whether to use it in its current state but the documentation links are broken so I'm unable to make that assessment. I'd appreciate any help!
